# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Piyush Jain
tagline:             'field notes'
description:         'Various learnings from research, analytics and programming. Hope you find something that helps. Using the < href="http://lanyon.getpoole.com" target="_blank"> theme based on <a href="http://jekyllrb.com" target="_blank">Jekyll</a> .'
url:                 http://piyushnz.github.io
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Piyush Jain
  url:               https://twitter.com/mdo
  email:             piyushnz@gmail.com

# Custom vars
version:             1.0.0
